/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardProfileRouteImport } from './routes/dashboard/profile'
import { Route as DashboardPharmacyRouteImport } from './routes/dashboard/pharmacy'
import { Route as DashboardMyPrescriptionsRouteImport } from './routes/dashboard/my-prescriptions'
import { Route as DashboardMyCalendarRouteImport } from './routes/dashboard/my-calendar'
import { Route as DashboardHomeRouteImport } from './routes/dashboard/home'
import { Route as DashboardDoctorsRouteImport } from './routes/dashboard/doctors'
import { Route as DashboardBillingRouteImport } from './routes/dashboard/billing'
import { Route as DashboardAppointmentsRouteImport } from './routes/dashboard/appointments'
import { Route as authAuthSignupRouteImport } from './routes/(auth)/auth-signup'
import { Route as authAuthSigninRouteImport } from './routes/(auth)/auth-signin'
import { Route as DashboardPharmacyDashboardIndexRouteImport } from './routes/dashboard/pharmacy-dashboard/index'
import { Route as DashboardOrdersIndexRouteImport } from './routes/dashboard/orders/index'
import { Route as DashboardDoctorIndexRouteImport } from './routes/dashboard/doctor/index'
import { Route as DashboardCartIndexRouteImport } from './routes/dashboard/cart/index'
import { Route as DashboardPharmacyDashboardPatientPrescriptionsRouteImport } from './routes/dashboard/pharmacy-dashboard/patient-prescriptions'
import { Route as DashboardPharmacyDashboardInventoryRouteImport } from './routes/dashboard/pharmacy-dashboard/inventory'
import { Route as DashboardPharmacyDashboardBillingRouteImport } from './routes/dashboard/pharmacy-dashboard/billing'
import { Route as DashboardOrdersOrderRouteImport } from './routes/dashboard/orders/$order'
import { Route as DashboardDoctorProfileRouteImport } from './routes/dashboard/doctor/profile'
import { Route as DashboardDoctorPrescriptionsRouteImport } from './routes/dashboard/doctor/prescriptions'
import { Route as DashboardDoctorPharmacyRouteImport } from './routes/dashboard/doctor/pharmacy'
import { Route as DashboardDoctorPatientsRouteImport } from './routes/dashboard/doctor/patients'
import { Route as DashboardDoctorCalendarRouteImport } from './routes/dashboard/doctor/calendar'
import { Route as DashboardCartNewOrderRouteImport } from './routes/dashboard/cart/new-order'
import { Route as DashboardPharmacyDashboardOrdersIndexRouteImport } from './routes/dashboard/pharmacy-dashboard/orders/index'
import { Route as DashboardDoctorDiagnosesIndexRouteImport } from './routes/dashboard/doctor/diagnoses/index'
import { Route as DashboardDoctorAppointmentsIndexRouteImport } from './routes/dashboard/doctor/appointments/index'
import { Route as DashboardPharmacyDashboardOrdersOrderRouteImport } from './routes/dashboard/pharmacy-dashboard/orders/$order'
import { Route as DashboardDoctorDiagnosesNewPrescriptionDgsRouteImport } from './routes/dashboard/doctor/diagnoses/new-prescription.$dgs'
import { Route as DashboardDoctorAppointmentsAppointmentAddDiagnosisRouteImport } from './routes/dashboard/doctor/appointments/$appointment.add-diagnosis'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPharmacyRoute = DashboardPharmacyRouteImport.update({
  id: '/pharmacy',
  path: '/pharmacy',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMyPrescriptionsRoute =
  DashboardMyPrescriptionsRouteImport.update({
    id: '/my-prescriptions',
    path: '/my-prescriptions',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardMyCalendarRoute = DashboardMyCalendarRouteImport.update({
  id: '/my-calendar',
  path: '/my-calendar',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHomeRoute = DashboardHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDoctorsRoute = DashboardDoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBillingRoute = DashboardBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAppointmentsRoute = DashboardAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => DashboardRoute,
} as any)
const authAuthSignupRoute = authAuthSignupRouteImport.update({
  id: '/(auth)/auth-signup',
  path: '/auth-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const authAuthSigninRoute = authAuthSigninRouteImport.update({
  id: '/(auth)/auth-signin',
  path: '/auth-signin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPharmacyDashboardIndexRoute =
  DashboardPharmacyDashboardIndexRouteImport.update({
    id: '/pharmacy-dashboard/',
    path: '/pharmacy-dashboard/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardOrdersIndexRoute = DashboardOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDoctorIndexRoute = DashboardDoctorIndexRouteImport.update({
  id: '/doctor/',
  path: '/doctor/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCartIndexRoute = DashboardCartIndexRouteImport.update({
  id: '/cart/',
  path: '/cart/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPharmacyDashboardPatientPrescriptionsRoute =
  DashboardPharmacyDashboardPatientPrescriptionsRouteImport.update({
    id: '/pharmacy-dashboard/patient-prescriptions',
    path: '/pharmacy-dashboard/patient-prescriptions',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardPharmacyDashboardInventoryRoute =
  DashboardPharmacyDashboardInventoryRouteImport.update({
    id: '/pharmacy-dashboard/inventory',
    path: '/pharmacy-dashboard/inventory',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardPharmacyDashboardBillingRoute =
  DashboardPharmacyDashboardBillingRouteImport.update({
    id: '/pharmacy-dashboard/billing',
    path: '/pharmacy-dashboard/billing',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardOrdersOrderRoute = DashboardOrdersOrderRouteImport.update({
  id: '/orders/$order',
  path: '/orders/$order',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDoctorProfileRoute = DashboardDoctorProfileRouteImport.update({
  id: '/doctor/profile',
  path: '/doctor/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDoctorPrescriptionsRoute =
  DashboardDoctorPrescriptionsRouteImport.update({
    id: '/doctor/prescriptions',
    path: '/doctor/prescriptions',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDoctorPharmacyRoute = DashboardDoctorPharmacyRouteImport.update({
  id: '/doctor/pharmacy',
  path: '/doctor/pharmacy',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDoctorPatientsRoute = DashboardDoctorPatientsRouteImport.update({
  id: '/doctor/patients',
  path: '/doctor/patients',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDoctorCalendarRoute = DashboardDoctorCalendarRouteImport.update({
  id: '/doctor/calendar',
  path: '/doctor/calendar',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCartNewOrderRoute = DashboardCartNewOrderRouteImport.update({
  id: '/cart/new-order',
  path: '/cart/new-order',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPharmacyDashboardOrdersIndexRoute =
  DashboardPharmacyDashboardOrdersIndexRouteImport.update({
    id: '/pharmacy-dashboard/orders/',
    path: '/pharmacy-dashboard/orders/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDoctorDiagnosesIndexRoute =
  DashboardDoctorDiagnosesIndexRouteImport.update({
    id: '/doctor/diagnoses/',
    path: '/doctor/diagnoses/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDoctorAppointmentsIndexRoute =
  DashboardDoctorAppointmentsIndexRouteImport.update({
    id: '/doctor/appointments/',
    path: '/doctor/appointments/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardPharmacyDashboardOrdersOrderRoute =
  DashboardPharmacyDashboardOrdersOrderRouteImport.update({
    id: '/pharmacy-dashboard/orders/$order',
    path: '/pharmacy-dashboard/orders/$order',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDoctorDiagnosesNewPrescriptionDgsRoute =
  DashboardDoctorDiagnosesNewPrescriptionDgsRouteImport.update({
    id: '/doctor/diagnoses/new-prescription/$dgs',
    path: '/doctor/diagnoses/new-prescription/$dgs',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDoctorAppointmentsAppointmentAddDiagnosisRoute =
  DashboardDoctorAppointmentsAppointmentAddDiagnosisRouteImport.update({
    id: '/doctor/appointments/$appointment/add-diagnosis',
    path: '/doctor/appointments/$appointment/add-diagnosis',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/auth-signin': typeof authAuthSigninRoute
  '/auth-signup': typeof authAuthSignupRoute
  '/dashboard/appointments': typeof DashboardAppointmentsRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/doctors': typeof DashboardDoctorsRoute
  '/dashboard/home': typeof DashboardHomeRoute
  '/dashboard/my-calendar': typeof DashboardMyCalendarRoute
  '/dashboard/my-prescriptions': typeof DashboardMyPrescriptionsRoute
  '/dashboard/pharmacy': typeof DashboardPharmacyRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/cart/new-order': typeof DashboardCartNewOrderRoute
  '/dashboard/doctor/calendar': typeof DashboardDoctorCalendarRoute
  '/dashboard/doctor/patients': typeof DashboardDoctorPatientsRoute
  '/dashboard/doctor/pharmacy': typeof DashboardDoctorPharmacyRoute
  '/dashboard/doctor/prescriptions': typeof DashboardDoctorPrescriptionsRoute
  '/dashboard/doctor/profile': typeof DashboardDoctorProfileRoute
  '/dashboard/orders/$order': typeof DashboardOrdersOrderRoute
  '/dashboard/pharmacy-dashboard/billing': typeof DashboardPharmacyDashboardBillingRoute
  '/dashboard/pharmacy-dashboard/inventory': typeof DashboardPharmacyDashboardInventoryRoute
  '/dashboard/pharmacy-dashboard/patient-prescriptions': typeof DashboardPharmacyDashboardPatientPrescriptionsRoute
  '/dashboard/cart': typeof DashboardCartIndexRoute
  '/dashboard/doctor': typeof DashboardDoctorIndexRoute
  '/dashboard/orders': typeof DashboardOrdersIndexRoute
  '/dashboard/pharmacy-dashboard': typeof DashboardPharmacyDashboardIndexRoute
  '/dashboard/pharmacy-dashboard/orders/$order': typeof DashboardPharmacyDashboardOrdersOrderRoute
  '/dashboard/doctor/appointments': typeof DashboardDoctorAppointmentsIndexRoute
  '/dashboard/doctor/diagnoses': typeof DashboardDoctorDiagnosesIndexRoute
  '/dashboard/pharmacy-dashboard/orders': typeof DashboardPharmacyDashboardOrdersIndexRoute
  '/dashboard/doctor/appointments/$appointment/add-diagnosis': typeof DashboardDoctorAppointmentsAppointmentAddDiagnosisRoute
  '/dashboard/doctor/diagnoses/new-prescription/$dgs': typeof DashboardDoctorDiagnosesNewPrescriptionDgsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/auth-signin': typeof authAuthSigninRoute
  '/auth-signup': typeof authAuthSignupRoute
  '/dashboard/appointments': typeof DashboardAppointmentsRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/doctors': typeof DashboardDoctorsRoute
  '/dashboard/home': typeof DashboardHomeRoute
  '/dashboard/my-calendar': typeof DashboardMyCalendarRoute
  '/dashboard/my-prescriptions': typeof DashboardMyPrescriptionsRoute
  '/dashboard/pharmacy': typeof DashboardPharmacyRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/cart/new-order': typeof DashboardCartNewOrderRoute
  '/dashboard/doctor/calendar': typeof DashboardDoctorCalendarRoute
  '/dashboard/doctor/patients': typeof DashboardDoctorPatientsRoute
  '/dashboard/doctor/pharmacy': typeof DashboardDoctorPharmacyRoute
  '/dashboard/doctor/prescriptions': typeof DashboardDoctorPrescriptionsRoute
  '/dashboard/doctor/profile': typeof DashboardDoctorProfileRoute
  '/dashboard/orders/$order': typeof DashboardOrdersOrderRoute
  '/dashboard/pharmacy-dashboard/billing': typeof DashboardPharmacyDashboardBillingRoute
  '/dashboard/pharmacy-dashboard/inventory': typeof DashboardPharmacyDashboardInventoryRoute
  '/dashboard/pharmacy-dashboard/patient-prescriptions': typeof DashboardPharmacyDashboardPatientPrescriptionsRoute
  '/dashboard/cart': typeof DashboardCartIndexRoute
  '/dashboard/doctor': typeof DashboardDoctorIndexRoute
  '/dashboard/orders': typeof DashboardOrdersIndexRoute
  '/dashboard/pharmacy-dashboard': typeof DashboardPharmacyDashboardIndexRoute
  '/dashboard/pharmacy-dashboard/orders/$order': typeof DashboardPharmacyDashboardOrdersOrderRoute
  '/dashboard/doctor/appointments': typeof DashboardDoctorAppointmentsIndexRoute
  '/dashboard/doctor/diagnoses': typeof DashboardDoctorDiagnosesIndexRoute
  '/dashboard/pharmacy-dashboard/orders': typeof DashboardPharmacyDashboardOrdersIndexRoute
  '/dashboard/doctor/appointments/$appointment/add-diagnosis': typeof DashboardDoctorAppointmentsAppointmentAddDiagnosisRoute
  '/dashboard/doctor/diagnoses/new-prescription/$dgs': typeof DashboardDoctorDiagnosesNewPrescriptionDgsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/(auth)/auth-signin': typeof authAuthSigninRoute
  '/(auth)/auth-signup': typeof authAuthSignupRoute
  '/dashboard/appointments': typeof DashboardAppointmentsRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/doctors': typeof DashboardDoctorsRoute
  '/dashboard/home': typeof DashboardHomeRoute
  '/dashboard/my-calendar': typeof DashboardMyCalendarRoute
  '/dashboard/my-prescriptions': typeof DashboardMyPrescriptionsRoute
  '/dashboard/pharmacy': typeof DashboardPharmacyRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/cart/new-order': typeof DashboardCartNewOrderRoute
  '/dashboard/doctor/calendar': typeof DashboardDoctorCalendarRoute
  '/dashboard/doctor/patients': typeof DashboardDoctorPatientsRoute
  '/dashboard/doctor/pharmacy': typeof DashboardDoctorPharmacyRoute
  '/dashboard/doctor/prescriptions': typeof DashboardDoctorPrescriptionsRoute
  '/dashboard/doctor/profile': typeof DashboardDoctorProfileRoute
  '/dashboard/orders/$order': typeof DashboardOrdersOrderRoute
  '/dashboard/pharmacy-dashboard/billing': typeof DashboardPharmacyDashboardBillingRoute
  '/dashboard/pharmacy-dashboard/inventory': typeof DashboardPharmacyDashboardInventoryRoute
  '/dashboard/pharmacy-dashboard/patient-prescriptions': typeof DashboardPharmacyDashboardPatientPrescriptionsRoute
  '/dashboard/cart/': typeof DashboardCartIndexRoute
  '/dashboard/doctor/': typeof DashboardDoctorIndexRoute
  '/dashboard/orders/': typeof DashboardOrdersIndexRoute
  '/dashboard/pharmacy-dashboard/': typeof DashboardPharmacyDashboardIndexRoute
  '/dashboard/pharmacy-dashboard/orders/$order': typeof DashboardPharmacyDashboardOrdersOrderRoute
  '/dashboard/doctor/appointments/': typeof DashboardDoctorAppointmentsIndexRoute
  '/dashboard/doctor/diagnoses/': typeof DashboardDoctorDiagnosesIndexRoute
  '/dashboard/pharmacy-dashboard/orders/': typeof DashboardPharmacyDashboardOrdersIndexRoute
  '/dashboard/doctor/appointments/$appointment/add-diagnosis': typeof DashboardDoctorAppointmentsAppointmentAddDiagnosisRoute
  '/dashboard/doctor/diagnoses/new-prescription/$dgs': typeof DashboardDoctorDiagnosesNewPrescriptionDgsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/auth-signin'
    | '/auth-signup'
    | '/dashboard/appointments'
    | '/dashboard/billing'
    | '/dashboard/doctors'
    | '/dashboard/home'
    | '/dashboard/my-calendar'
    | '/dashboard/my-prescriptions'
    | '/dashboard/pharmacy'
    | '/dashboard/profile'
    | '/dashboard/cart/new-order'
    | '/dashboard/doctor/calendar'
    | '/dashboard/doctor/patients'
    | '/dashboard/doctor/pharmacy'
    | '/dashboard/doctor/prescriptions'
    | '/dashboard/doctor/profile'
    | '/dashboard/orders/$order'
    | '/dashboard/pharmacy-dashboard/billing'
    | '/dashboard/pharmacy-dashboard/inventory'
    | '/dashboard/pharmacy-dashboard/patient-prescriptions'
    | '/dashboard/cart'
    | '/dashboard/doctor'
    | '/dashboard/orders'
    | '/dashboard/pharmacy-dashboard'
    | '/dashboard/pharmacy-dashboard/orders/$order'
    | '/dashboard/doctor/appointments'
    | '/dashboard/doctor/diagnoses'
    | '/dashboard/pharmacy-dashboard/orders'
    | '/dashboard/doctor/appointments/$appointment/add-diagnosis'
    | '/dashboard/doctor/diagnoses/new-prescription/$dgs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/auth-signin'
    | '/auth-signup'
    | '/dashboard/appointments'
    | '/dashboard/billing'
    | '/dashboard/doctors'
    | '/dashboard/home'
    | '/dashboard/my-calendar'
    | '/dashboard/my-prescriptions'
    | '/dashboard/pharmacy'
    | '/dashboard/profile'
    | '/dashboard/cart/new-order'
    | '/dashboard/doctor/calendar'
    | '/dashboard/doctor/patients'
    | '/dashboard/doctor/pharmacy'
    | '/dashboard/doctor/prescriptions'
    | '/dashboard/doctor/profile'
    | '/dashboard/orders/$order'
    | '/dashboard/pharmacy-dashboard/billing'
    | '/dashboard/pharmacy-dashboard/inventory'
    | '/dashboard/pharmacy-dashboard/patient-prescriptions'
    | '/dashboard/cart'
    | '/dashboard/doctor'
    | '/dashboard/orders'
    | '/dashboard/pharmacy-dashboard'
    | '/dashboard/pharmacy-dashboard/orders/$order'
    | '/dashboard/doctor/appointments'
    | '/dashboard/doctor/diagnoses'
    | '/dashboard/pharmacy-dashboard/orders'
    | '/dashboard/doctor/appointments/$appointment/add-diagnosis'
    | '/dashboard/doctor/diagnoses/new-prescription/$dgs'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/(auth)/auth-signin'
    | '/(auth)/auth-signup'
    | '/dashboard/appointments'
    | '/dashboard/billing'
    | '/dashboard/doctors'
    | '/dashboard/home'
    | '/dashboard/my-calendar'
    | '/dashboard/my-prescriptions'
    | '/dashboard/pharmacy'
    | '/dashboard/profile'
    | '/dashboard/cart/new-order'
    | '/dashboard/doctor/calendar'
    | '/dashboard/doctor/patients'
    | '/dashboard/doctor/pharmacy'
    | '/dashboard/doctor/prescriptions'
    | '/dashboard/doctor/profile'
    | '/dashboard/orders/$order'
    | '/dashboard/pharmacy-dashboard/billing'
    | '/dashboard/pharmacy-dashboard/inventory'
    | '/dashboard/pharmacy-dashboard/patient-prescriptions'
    | '/dashboard/cart/'
    | '/dashboard/doctor/'
    | '/dashboard/orders/'
    | '/dashboard/pharmacy-dashboard/'
    | '/dashboard/pharmacy-dashboard/orders/$order'
    | '/dashboard/doctor/appointments/'
    | '/dashboard/doctor/diagnoses/'
    | '/dashboard/pharmacy-dashboard/orders/'
    | '/dashboard/doctor/appointments/$appointment/add-diagnosis'
    | '/dashboard/doctor/diagnoses/new-prescription/$dgs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  authAuthSigninRoute: typeof authAuthSigninRoute
  authAuthSignupRoute: typeof authAuthSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/pharmacy': {
      id: '/dashboard/pharmacy'
      path: '/pharmacy'
      fullPath: '/dashboard/pharmacy'
      preLoaderRoute: typeof DashboardPharmacyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/my-prescriptions': {
      id: '/dashboard/my-prescriptions'
      path: '/my-prescriptions'
      fullPath: '/dashboard/my-prescriptions'
      preLoaderRoute: typeof DashboardMyPrescriptionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/my-calendar': {
      id: '/dashboard/my-calendar'
      path: '/my-calendar'
      fullPath: '/dashboard/my-calendar'
      preLoaderRoute: typeof DashboardMyCalendarRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/home': {
      id: '/dashboard/home'
      path: '/home'
      fullPath: '/dashboard/home'
      preLoaderRoute: typeof DashboardHomeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/doctors': {
      id: '/dashboard/doctors'
      path: '/doctors'
      fullPath: '/dashboard/doctors'
      preLoaderRoute: typeof DashboardDoctorsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/billing': {
      id: '/dashboard/billing'
      path: '/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof DashboardBillingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/appointments': {
      id: '/dashboard/appointments'
      path: '/appointments'
      fullPath: '/dashboard/appointments'
      preLoaderRoute: typeof DashboardAppointmentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/(auth)/auth-signup': {
      id: '/(auth)/auth-signup'
      path: '/auth-signup'
      fullPath: '/auth-signup'
      preLoaderRoute: typeof authAuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/auth-signin': {
      id: '/(auth)/auth-signin'
      path: '/auth-signin'
      fullPath: '/auth-signin'
      preLoaderRoute: typeof authAuthSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/pharmacy-dashboard/': {
      id: '/dashboard/pharmacy-dashboard/'
      path: '/pharmacy-dashboard'
      fullPath: '/dashboard/pharmacy-dashboard'
      preLoaderRoute: typeof DashboardPharmacyDashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/orders/': {
      id: '/dashboard/orders/'
      path: '/orders'
      fullPath: '/dashboard/orders'
      preLoaderRoute: typeof DashboardOrdersIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/doctor/': {
      id: '/dashboard/doctor/'
      path: '/doctor'
      fullPath: '/dashboard/doctor'
      preLoaderRoute: typeof DashboardDoctorIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/cart/': {
      id: '/dashboard/cart/'
      path: '/cart'
      fullPath: '/dashboard/cart'
      preLoaderRoute: typeof DashboardCartIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/pharmacy-dashboard/patient-prescriptions': {
      id: '/dashboard/pharmacy-dashboard/patient-prescriptions'
      path: '/pharmacy-dashboard/patient-prescriptions'
      fullPath: '/dashboard/pharmacy-dashboard/patient-prescriptions'
      preLoaderRoute: typeof DashboardPharmacyDashboardPatientPrescriptionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/pharmacy-dashboard/inventory': {
      id: '/dashboard/pharmacy-dashboard/inventory'
      path: '/pharmacy-dashboard/inventory'
      fullPath: '/dashboard/pharmacy-dashboard/inventory'
      preLoaderRoute: typeof DashboardPharmacyDashboardInventoryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/pharmacy-dashboard/billing': {
      id: '/dashboard/pharmacy-dashboard/billing'
      path: '/pharmacy-dashboard/billing'
      fullPath: '/dashboard/pharmacy-dashboard/billing'
      preLoaderRoute: typeof DashboardPharmacyDashboardBillingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/orders/$order': {
      id: '/dashboard/orders/$order'
      path: '/orders/$order'
      fullPath: '/dashboard/orders/$order'
      preLoaderRoute: typeof DashboardOrdersOrderRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/doctor/profile': {
      id: '/dashboard/doctor/profile'
      path: '/doctor/profile'
      fullPath: '/dashboard/doctor/profile'
      preLoaderRoute: typeof DashboardDoctorProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/doctor/prescriptions': {
      id: '/dashboard/doctor/prescriptions'
      path: '/doctor/prescriptions'
      fullPath: '/dashboard/doctor/prescriptions'
      preLoaderRoute: typeof DashboardDoctorPrescriptionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/doctor/pharmacy': {
      id: '/dashboard/doctor/pharmacy'
      path: '/doctor/pharmacy'
      fullPath: '/dashboard/doctor/pharmacy'
      preLoaderRoute: typeof DashboardDoctorPharmacyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/doctor/patients': {
      id: '/dashboard/doctor/patients'
      path: '/doctor/patients'
      fullPath: '/dashboard/doctor/patients'
      preLoaderRoute: typeof DashboardDoctorPatientsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/doctor/calendar': {
      id: '/dashboard/doctor/calendar'
      path: '/doctor/calendar'
      fullPath: '/dashboard/doctor/calendar'
      preLoaderRoute: typeof DashboardDoctorCalendarRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/cart/new-order': {
      id: '/dashboard/cart/new-order'
      path: '/cart/new-order'
      fullPath: '/dashboard/cart/new-order'
      preLoaderRoute: typeof DashboardCartNewOrderRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/pharmacy-dashboard/orders/': {
      id: '/dashboard/pharmacy-dashboard/orders/'
      path: '/pharmacy-dashboard/orders'
      fullPath: '/dashboard/pharmacy-dashboard/orders'
      preLoaderRoute: typeof DashboardPharmacyDashboardOrdersIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/doctor/diagnoses/': {
      id: '/dashboard/doctor/diagnoses/'
      path: '/doctor/diagnoses'
      fullPath: '/dashboard/doctor/diagnoses'
      preLoaderRoute: typeof DashboardDoctorDiagnosesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/doctor/appointments/': {
      id: '/dashboard/doctor/appointments/'
      path: '/doctor/appointments'
      fullPath: '/dashboard/doctor/appointments'
      preLoaderRoute: typeof DashboardDoctorAppointmentsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/pharmacy-dashboard/orders/$order': {
      id: '/dashboard/pharmacy-dashboard/orders/$order'
      path: '/pharmacy-dashboard/orders/$order'
      fullPath: '/dashboard/pharmacy-dashboard/orders/$order'
      preLoaderRoute: typeof DashboardPharmacyDashboardOrdersOrderRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/doctor/diagnoses/new-prescription/$dgs': {
      id: '/dashboard/doctor/diagnoses/new-prescription/$dgs'
      path: '/doctor/diagnoses/new-prescription/$dgs'
      fullPath: '/dashboard/doctor/diagnoses/new-prescription/$dgs'
      preLoaderRoute: typeof DashboardDoctorDiagnosesNewPrescriptionDgsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/doctor/appointments/$appointment/add-diagnosis': {
      id: '/dashboard/doctor/appointments/$appointment/add-diagnosis'
      path: '/doctor/appointments/$appointment/add-diagnosis'
      fullPath: '/dashboard/doctor/appointments/$appointment/add-diagnosis'
      preLoaderRoute: typeof DashboardDoctorAppointmentsAppointmentAddDiagnosisRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAppointmentsRoute: typeof DashboardAppointmentsRoute
  DashboardBillingRoute: typeof DashboardBillingRoute
  DashboardDoctorsRoute: typeof DashboardDoctorsRoute
  DashboardHomeRoute: typeof DashboardHomeRoute
  DashboardMyCalendarRoute: typeof DashboardMyCalendarRoute
  DashboardMyPrescriptionsRoute: typeof DashboardMyPrescriptionsRoute
  DashboardPharmacyRoute: typeof DashboardPharmacyRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardCartNewOrderRoute: typeof DashboardCartNewOrderRoute
  DashboardDoctorCalendarRoute: typeof DashboardDoctorCalendarRoute
  DashboardDoctorPatientsRoute: typeof DashboardDoctorPatientsRoute
  DashboardDoctorPharmacyRoute: typeof DashboardDoctorPharmacyRoute
  DashboardDoctorPrescriptionsRoute: typeof DashboardDoctorPrescriptionsRoute
  DashboardDoctorProfileRoute: typeof DashboardDoctorProfileRoute
  DashboardOrdersOrderRoute: typeof DashboardOrdersOrderRoute
  DashboardPharmacyDashboardBillingRoute: typeof DashboardPharmacyDashboardBillingRoute
  DashboardPharmacyDashboardInventoryRoute: typeof DashboardPharmacyDashboardInventoryRoute
  DashboardPharmacyDashboardPatientPrescriptionsRoute: typeof DashboardPharmacyDashboardPatientPrescriptionsRoute
  DashboardCartIndexRoute: typeof DashboardCartIndexRoute
  DashboardDoctorIndexRoute: typeof DashboardDoctorIndexRoute
  DashboardOrdersIndexRoute: typeof DashboardOrdersIndexRoute
  DashboardPharmacyDashboardIndexRoute: typeof DashboardPharmacyDashboardIndexRoute
  DashboardPharmacyDashboardOrdersOrderRoute: typeof DashboardPharmacyDashboardOrdersOrderRoute
  DashboardDoctorAppointmentsIndexRoute: typeof DashboardDoctorAppointmentsIndexRoute
  DashboardDoctorDiagnosesIndexRoute: typeof DashboardDoctorDiagnosesIndexRoute
  DashboardPharmacyDashboardOrdersIndexRoute: typeof DashboardPharmacyDashboardOrdersIndexRoute
  DashboardDoctorAppointmentsAppointmentAddDiagnosisRoute: typeof DashboardDoctorAppointmentsAppointmentAddDiagnosisRoute
  DashboardDoctorDiagnosesNewPrescriptionDgsRoute: typeof DashboardDoctorDiagnosesNewPrescriptionDgsRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAppointmentsRoute: DashboardAppointmentsRoute,
  DashboardBillingRoute: DashboardBillingRoute,
  DashboardDoctorsRoute: DashboardDoctorsRoute,
  DashboardHomeRoute: DashboardHomeRoute,
  DashboardMyCalendarRoute: DashboardMyCalendarRoute,
  DashboardMyPrescriptionsRoute: DashboardMyPrescriptionsRoute,
  DashboardPharmacyRoute: DashboardPharmacyRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardCartNewOrderRoute: DashboardCartNewOrderRoute,
  DashboardDoctorCalendarRoute: DashboardDoctorCalendarRoute,
  DashboardDoctorPatientsRoute: DashboardDoctorPatientsRoute,
  DashboardDoctorPharmacyRoute: DashboardDoctorPharmacyRoute,
  DashboardDoctorPrescriptionsRoute: DashboardDoctorPrescriptionsRoute,
  DashboardDoctorProfileRoute: DashboardDoctorProfileRoute,
  DashboardOrdersOrderRoute: DashboardOrdersOrderRoute,
  DashboardPharmacyDashboardBillingRoute:
    DashboardPharmacyDashboardBillingRoute,
  DashboardPharmacyDashboardInventoryRoute:
    DashboardPharmacyDashboardInventoryRoute,
  DashboardPharmacyDashboardPatientPrescriptionsRoute:
    DashboardPharmacyDashboardPatientPrescriptionsRoute,
  DashboardCartIndexRoute: DashboardCartIndexRoute,
  DashboardDoctorIndexRoute: DashboardDoctorIndexRoute,
  DashboardOrdersIndexRoute: DashboardOrdersIndexRoute,
  DashboardPharmacyDashboardIndexRoute: DashboardPharmacyDashboardIndexRoute,
  DashboardPharmacyDashboardOrdersOrderRoute:
    DashboardPharmacyDashboardOrdersOrderRoute,
  DashboardDoctorAppointmentsIndexRoute: DashboardDoctorAppointmentsIndexRoute,
  DashboardDoctorDiagnosesIndexRoute: DashboardDoctorDiagnosesIndexRoute,
  DashboardPharmacyDashboardOrdersIndexRoute:
    DashboardPharmacyDashboardOrdersIndexRoute,
  DashboardDoctorAppointmentsAppointmentAddDiagnosisRoute:
    DashboardDoctorAppointmentsAppointmentAddDiagnosisRoute,
  DashboardDoctorDiagnosesNewPrescriptionDgsRoute:
    DashboardDoctorDiagnosesNewPrescriptionDgsRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  authAuthSigninRoute: authAuthSigninRoute,
  authAuthSignupRoute: authAuthSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
