/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OurDoctorsRouteImport } from './routes/our-doctors'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardProfileRouteImport } from './routes/dashboard/profile'
import { Route as DashboardPharmacyRouteImport } from './routes/dashboard/pharmacy'
import { Route as DashboardMyPrescriptionsRouteImport } from './routes/dashboard/my-prescriptions'
import { Route as DashboardMyCalendarRouteImport } from './routes/dashboard/my-calendar'
import { Route as DashboardHomeRouteImport } from './routes/dashboard/home'
import { Route as DashboardDoctorsRouteImport } from './routes/dashboard/doctors'
import { Route as DashboardChatRouteImport } from './routes/dashboard/chat'
import { Route as DashboardBillingRouteImport } from './routes/dashboard/billing'
import { Route as DashboardAppointmentsRouteImport } from './routes/dashboard/appointments'
import { Route as authAuthSignupRouteImport } from './routes/(auth)/auth-signup'
import { Route as authAuthSigninRouteImport } from './routes/(auth)/auth-signin'
import { Route as DashboardOrdersIndexRouteImport } from './routes/dashboard/orders/index'
import { Route as DashboardDoctorIndexRouteImport } from './routes/dashboard/doctor/index'
import { Route as DashboardCartIndexRouteImport } from './routes/dashboard/cart/index'
import { Route as DashboardAdminIndexRouteImport } from './routes/dashboard/admin/index'
import { Route as DashboardOrdersOrderRouteImport } from './routes/dashboard/orders/$order'
import { Route as DashboardDoctorProfileRouteImport } from './routes/dashboard/doctor/profile'
import { Route as DashboardDoctorPrescriptionsRouteImport } from './routes/dashboard/doctor/prescriptions'
import { Route as DashboardDoctorPharmacyRouteImport } from './routes/dashboard/doctor/pharmacy'
import { Route as DashboardDoctorPatientsRouteImport } from './routes/dashboard/doctor/patients'
import { Route as DashboardDoctorChatRouteImport } from './routes/dashboard/doctor/chat'
import { Route as DashboardDoctorCalendarRouteImport } from './routes/dashboard/doctor/calendar'
import { Route as DashboardCartNewOrderRouteImport } from './routes/dashboard/cart/new-order'
import { Route as DashboardAdminPrescriptionsRouteImport } from './routes/dashboard/admin/prescriptions'
import { Route as DashboardAdminPharmacyRouteImport } from './routes/dashboard/admin/pharmacy'
import { Route as DashboardAdminPatientsRouteImport } from './routes/dashboard/admin/patients'
import { Route as DashboardAdminInventoryRouteImport } from './routes/dashboard/admin/inventory'
import { Route as DashboardAdminBillingRouteImport } from './routes/dashboard/admin/billing'
import { Route as DashboardDoctorDiagnosesIndexRouteImport } from './routes/dashboard/doctor/diagnoses/index'
import { Route as DashboardDoctorAppointmentsIndexRouteImport } from './routes/dashboard/doctor/appointments/index'
import { Route as DashboardAdminOrdersIndexRouteImport } from './routes/dashboard/admin/orders/index'
import { Route as DashboardAdminDoctorIndexRouteImport } from './routes/dashboard/admin/doctor/index'
import { Route as DashboardAdminOrdersOrderRouteImport } from './routes/dashboard/admin/orders/$order'
import { Route as DashboardAdminDoctorNewRouteImport } from './routes/dashboard/admin/doctor/new'
import { Route as DashboardDoctorDiagnosesNewPrescriptionDgsRouteImport } from './routes/dashboard/doctor/diagnoses/new-prescription.$dgs'
import { Route as DashboardDoctorAppointmentsAppointmentAddDiagnosisRouteImport } from './routes/dashboard/doctor/appointments/$appointment.add-diagnosis'

const OurDoctorsRoute = OurDoctorsRouteImport.update({
  id: '/our-doctors',
  path: '/our-doctors',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPharmacyRoute = DashboardPharmacyRouteImport.update({
  id: '/pharmacy',
  path: '/pharmacy',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMyPrescriptionsRoute =
  DashboardMyPrescriptionsRouteImport.update({
    id: '/my-prescriptions',
    path: '/my-prescriptions',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardMyCalendarRoute = DashboardMyCalendarRouteImport.update({
  id: '/my-calendar',
  path: '/my-calendar',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHomeRoute = DashboardHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDoctorsRoute = DashboardDoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardChatRoute = DashboardChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBillingRoute = DashboardBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAppointmentsRoute = DashboardAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => DashboardRoute,
} as any)
const authAuthSignupRoute = authAuthSignupRouteImport.update({
  id: '/(auth)/auth-signup',
  path: '/auth-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const authAuthSigninRoute = authAuthSigninRouteImport.update({
  id: '/(auth)/auth-signin',
  path: '/auth-signin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardOrdersIndexRoute = DashboardOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDoctorIndexRoute = DashboardDoctorIndexRouteImport.update({
  id: '/doctor/',
  path: '/doctor/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCartIndexRoute = DashboardCartIndexRouteImport.update({
  id: '/cart/',
  path: '/cart/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminIndexRoute = DashboardAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOrdersOrderRoute = DashboardOrdersOrderRouteImport.update({
  id: '/orders/$order',
  path: '/orders/$order',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDoctorProfileRoute = DashboardDoctorProfileRouteImport.update({
  id: '/doctor/profile',
  path: '/doctor/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDoctorPrescriptionsRoute =
  DashboardDoctorPrescriptionsRouteImport.update({
    id: '/doctor/prescriptions',
    path: '/doctor/prescriptions',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDoctorPharmacyRoute = DashboardDoctorPharmacyRouteImport.update({
  id: '/doctor/pharmacy',
  path: '/doctor/pharmacy',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDoctorPatientsRoute = DashboardDoctorPatientsRouteImport.update({
  id: '/doctor/patients',
  path: '/doctor/patients',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDoctorChatRoute = DashboardDoctorChatRouteImport.update({
  id: '/doctor/chat',
  path: '/doctor/chat',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDoctorCalendarRoute = DashboardDoctorCalendarRouteImport.update({
  id: '/doctor/calendar',
  path: '/doctor/calendar',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCartNewOrderRoute = DashboardCartNewOrderRouteImport.update({
  id: '/cart/new-order',
  path: '/cart/new-order',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminPrescriptionsRoute =
  DashboardAdminPrescriptionsRouteImport.update({
    id: '/admin/prescriptions',
    path: '/admin/prescriptions',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminPharmacyRoute = DashboardAdminPharmacyRouteImport.update({
  id: '/admin/pharmacy',
  path: '/admin/pharmacy',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminPatientsRoute = DashboardAdminPatientsRouteImport.update({
  id: '/admin/patients',
  path: '/admin/patients',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminInventoryRoute = DashboardAdminInventoryRouteImport.update({
  id: '/admin/inventory',
  path: '/admin/inventory',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminBillingRoute = DashboardAdminBillingRouteImport.update({
  id: '/admin/billing',
  path: '/admin/billing',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDoctorDiagnosesIndexRoute =
  DashboardDoctorDiagnosesIndexRouteImport.update({
    id: '/doctor/diagnoses/',
    path: '/doctor/diagnoses/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDoctorAppointmentsIndexRoute =
  DashboardDoctorAppointmentsIndexRouteImport.update({
    id: '/doctor/appointments/',
    path: '/doctor/appointments/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminOrdersIndexRoute =
  DashboardAdminOrdersIndexRouteImport.update({
    id: '/admin/orders/',
    path: '/admin/orders/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminDoctorIndexRoute =
  DashboardAdminDoctorIndexRouteImport.update({
    id: '/admin/doctor/',
    path: '/admin/doctor/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminOrdersOrderRoute =
  DashboardAdminOrdersOrderRouteImport.update({
    id: '/admin/orders/$order',
    path: '/admin/orders/$order',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminDoctorNewRoute = DashboardAdminDoctorNewRouteImport.update({
  id: '/admin/doctor/new',
  path: '/admin/doctor/new',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDoctorDiagnosesNewPrescriptionDgsRoute =
  DashboardDoctorDiagnosesNewPrescriptionDgsRouteImport.update({
    id: '/doctor/diagnoses/new-prescription/$dgs',
    path: '/doctor/diagnoses/new-prescription/$dgs',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDoctorAppointmentsAppointmentAddDiagnosisRoute =
  DashboardDoctorAppointmentsAppointmentAddDiagnosisRouteImport.update({
    id: '/doctor/appointments/$appointment/add-diagnosis',
    path: '/doctor/appointments/$appointment/add-diagnosis',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/our-doctors': typeof OurDoctorsRoute
  '/auth-signin': typeof authAuthSigninRoute
  '/auth-signup': typeof authAuthSignupRoute
  '/dashboard/appointments': typeof DashboardAppointmentsRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/chat': typeof DashboardChatRoute
  '/dashboard/doctors': typeof DashboardDoctorsRoute
  '/dashboard/home': typeof DashboardHomeRoute
  '/dashboard/my-calendar': typeof DashboardMyCalendarRoute
  '/dashboard/my-prescriptions': typeof DashboardMyPrescriptionsRoute
  '/dashboard/pharmacy': typeof DashboardPharmacyRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/admin/billing': typeof DashboardAdminBillingRoute
  '/dashboard/admin/inventory': typeof DashboardAdminInventoryRoute
  '/dashboard/admin/patients': typeof DashboardAdminPatientsRoute
  '/dashboard/admin/pharmacy': typeof DashboardAdminPharmacyRoute
  '/dashboard/admin/prescriptions': typeof DashboardAdminPrescriptionsRoute
  '/dashboard/cart/new-order': typeof DashboardCartNewOrderRoute
  '/dashboard/doctor/calendar': typeof DashboardDoctorCalendarRoute
  '/dashboard/doctor/chat': typeof DashboardDoctorChatRoute
  '/dashboard/doctor/patients': typeof DashboardDoctorPatientsRoute
  '/dashboard/doctor/pharmacy': typeof DashboardDoctorPharmacyRoute
  '/dashboard/doctor/prescriptions': typeof DashboardDoctorPrescriptionsRoute
  '/dashboard/doctor/profile': typeof DashboardDoctorProfileRoute
  '/dashboard/orders/$order': typeof DashboardOrdersOrderRoute
  '/dashboard/admin': typeof DashboardAdminIndexRoute
  '/dashboard/cart': typeof DashboardCartIndexRoute
  '/dashboard/doctor': typeof DashboardDoctorIndexRoute
  '/dashboard/orders': typeof DashboardOrdersIndexRoute
  '/dashboard/admin/doctor/new': typeof DashboardAdminDoctorNewRoute
  '/dashboard/admin/orders/$order': typeof DashboardAdminOrdersOrderRoute
  '/dashboard/admin/doctor': typeof DashboardAdminDoctorIndexRoute
  '/dashboard/admin/orders': typeof DashboardAdminOrdersIndexRoute
  '/dashboard/doctor/appointments': typeof DashboardDoctorAppointmentsIndexRoute
  '/dashboard/doctor/diagnoses': typeof DashboardDoctorDiagnosesIndexRoute
  '/dashboard/doctor/appointments/$appointment/add-diagnosis': typeof DashboardDoctorAppointmentsAppointmentAddDiagnosisRoute
  '/dashboard/doctor/diagnoses/new-prescription/$dgs': typeof DashboardDoctorDiagnosesNewPrescriptionDgsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/our-doctors': typeof OurDoctorsRoute
  '/auth-signin': typeof authAuthSigninRoute
  '/auth-signup': typeof authAuthSignupRoute
  '/dashboard/appointments': typeof DashboardAppointmentsRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/chat': typeof DashboardChatRoute
  '/dashboard/doctors': typeof DashboardDoctorsRoute
  '/dashboard/home': typeof DashboardHomeRoute
  '/dashboard/my-calendar': typeof DashboardMyCalendarRoute
  '/dashboard/my-prescriptions': typeof DashboardMyPrescriptionsRoute
  '/dashboard/pharmacy': typeof DashboardPharmacyRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/admin/billing': typeof DashboardAdminBillingRoute
  '/dashboard/admin/inventory': typeof DashboardAdminInventoryRoute
  '/dashboard/admin/patients': typeof DashboardAdminPatientsRoute
  '/dashboard/admin/pharmacy': typeof DashboardAdminPharmacyRoute
  '/dashboard/admin/prescriptions': typeof DashboardAdminPrescriptionsRoute
  '/dashboard/cart/new-order': typeof DashboardCartNewOrderRoute
  '/dashboard/doctor/calendar': typeof DashboardDoctorCalendarRoute
  '/dashboard/doctor/chat': typeof DashboardDoctorChatRoute
  '/dashboard/doctor/patients': typeof DashboardDoctorPatientsRoute
  '/dashboard/doctor/pharmacy': typeof DashboardDoctorPharmacyRoute
  '/dashboard/doctor/prescriptions': typeof DashboardDoctorPrescriptionsRoute
  '/dashboard/doctor/profile': typeof DashboardDoctorProfileRoute
  '/dashboard/orders/$order': typeof DashboardOrdersOrderRoute
  '/dashboard/admin': typeof DashboardAdminIndexRoute
  '/dashboard/cart': typeof DashboardCartIndexRoute
  '/dashboard/doctor': typeof DashboardDoctorIndexRoute
  '/dashboard/orders': typeof DashboardOrdersIndexRoute
  '/dashboard/admin/doctor/new': typeof DashboardAdminDoctorNewRoute
  '/dashboard/admin/orders/$order': typeof DashboardAdminOrdersOrderRoute
  '/dashboard/admin/doctor': typeof DashboardAdminDoctorIndexRoute
  '/dashboard/admin/orders': typeof DashboardAdminOrdersIndexRoute
  '/dashboard/doctor/appointments': typeof DashboardDoctorAppointmentsIndexRoute
  '/dashboard/doctor/diagnoses': typeof DashboardDoctorDiagnosesIndexRoute
  '/dashboard/doctor/appointments/$appointment/add-diagnosis': typeof DashboardDoctorAppointmentsAppointmentAddDiagnosisRoute
  '/dashboard/doctor/diagnoses/new-prescription/$dgs': typeof DashboardDoctorDiagnosesNewPrescriptionDgsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/our-doctors': typeof OurDoctorsRoute
  '/(auth)/auth-signin': typeof authAuthSigninRoute
  '/(auth)/auth-signup': typeof authAuthSignupRoute
  '/dashboard/appointments': typeof DashboardAppointmentsRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/chat': typeof DashboardChatRoute
  '/dashboard/doctors': typeof DashboardDoctorsRoute
  '/dashboard/home': typeof DashboardHomeRoute
  '/dashboard/my-calendar': typeof DashboardMyCalendarRoute
  '/dashboard/my-prescriptions': typeof DashboardMyPrescriptionsRoute
  '/dashboard/pharmacy': typeof DashboardPharmacyRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/admin/billing': typeof DashboardAdminBillingRoute
  '/dashboard/admin/inventory': typeof DashboardAdminInventoryRoute
  '/dashboard/admin/patients': typeof DashboardAdminPatientsRoute
  '/dashboard/admin/pharmacy': typeof DashboardAdminPharmacyRoute
  '/dashboard/admin/prescriptions': typeof DashboardAdminPrescriptionsRoute
  '/dashboard/cart/new-order': typeof DashboardCartNewOrderRoute
  '/dashboard/doctor/calendar': typeof DashboardDoctorCalendarRoute
  '/dashboard/doctor/chat': typeof DashboardDoctorChatRoute
  '/dashboard/doctor/patients': typeof DashboardDoctorPatientsRoute
  '/dashboard/doctor/pharmacy': typeof DashboardDoctorPharmacyRoute
  '/dashboard/doctor/prescriptions': typeof DashboardDoctorPrescriptionsRoute
  '/dashboard/doctor/profile': typeof DashboardDoctorProfileRoute
  '/dashboard/orders/$order': typeof DashboardOrdersOrderRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/cart/': typeof DashboardCartIndexRoute
  '/dashboard/doctor/': typeof DashboardDoctorIndexRoute
  '/dashboard/orders/': typeof DashboardOrdersIndexRoute
  '/dashboard/admin/doctor/new': typeof DashboardAdminDoctorNewRoute
  '/dashboard/admin/orders/$order': typeof DashboardAdminOrdersOrderRoute
  '/dashboard/admin/doctor/': typeof DashboardAdminDoctorIndexRoute
  '/dashboard/admin/orders/': typeof DashboardAdminOrdersIndexRoute
  '/dashboard/doctor/appointments/': typeof DashboardDoctorAppointmentsIndexRoute
  '/dashboard/doctor/diagnoses/': typeof DashboardDoctorDiagnosesIndexRoute
  '/dashboard/doctor/appointments/$appointment/add-diagnosis': typeof DashboardDoctorAppointmentsAppointmentAddDiagnosisRoute
  '/dashboard/doctor/diagnoses/new-prescription/$dgs': typeof DashboardDoctorDiagnosesNewPrescriptionDgsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/our-doctors'
    | '/auth-signin'
    | '/auth-signup'
    | '/dashboard/appointments'
    | '/dashboard/billing'
    | '/dashboard/chat'
    | '/dashboard/doctors'
    | '/dashboard/home'
    | '/dashboard/my-calendar'
    | '/dashboard/my-prescriptions'
    | '/dashboard/pharmacy'
    | '/dashboard/profile'
    | '/dashboard/admin/billing'
    | '/dashboard/admin/inventory'
    | '/dashboard/admin/patients'
    | '/dashboard/admin/pharmacy'
    | '/dashboard/admin/prescriptions'
    | '/dashboard/cart/new-order'
    | '/dashboard/doctor/calendar'
    | '/dashboard/doctor/chat'
    | '/dashboard/doctor/patients'
    | '/dashboard/doctor/pharmacy'
    | '/dashboard/doctor/prescriptions'
    | '/dashboard/doctor/profile'
    | '/dashboard/orders/$order'
    | '/dashboard/admin'
    | '/dashboard/cart'
    | '/dashboard/doctor'
    | '/dashboard/orders'
    | '/dashboard/admin/doctor/new'
    | '/dashboard/admin/orders/$order'
    | '/dashboard/admin/doctor'
    | '/dashboard/admin/orders'
    | '/dashboard/doctor/appointments'
    | '/dashboard/doctor/diagnoses'
    | '/dashboard/doctor/appointments/$appointment/add-diagnosis'
    | '/dashboard/doctor/diagnoses/new-prescription/$dgs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/our-doctors'
    | '/auth-signin'
    | '/auth-signup'
    | '/dashboard/appointments'
    | '/dashboard/billing'
    | '/dashboard/chat'
    | '/dashboard/doctors'
    | '/dashboard/home'
    | '/dashboard/my-calendar'
    | '/dashboard/my-prescriptions'
    | '/dashboard/pharmacy'
    | '/dashboard/profile'
    | '/dashboard/admin/billing'
    | '/dashboard/admin/inventory'
    | '/dashboard/admin/patients'
    | '/dashboard/admin/pharmacy'
    | '/dashboard/admin/prescriptions'
    | '/dashboard/cart/new-order'
    | '/dashboard/doctor/calendar'
    | '/dashboard/doctor/chat'
    | '/dashboard/doctor/patients'
    | '/dashboard/doctor/pharmacy'
    | '/dashboard/doctor/prescriptions'
    | '/dashboard/doctor/profile'
    | '/dashboard/orders/$order'
    | '/dashboard/admin'
    | '/dashboard/cart'
    | '/dashboard/doctor'
    | '/dashboard/orders'
    | '/dashboard/admin/doctor/new'
    | '/dashboard/admin/orders/$order'
    | '/dashboard/admin/doctor'
    | '/dashboard/admin/orders'
    | '/dashboard/doctor/appointments'
    | '/dashboard/doctor/diagnoses'
    | '/dashboard/doctor/appointments/$appointment/add-diagnosis'
    | '/dashboard/doctor/diagnoses/new-prescription/$dgs'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/our-doctors'
    | '/(auth)/auth-signin'
    | '/(auth)/auth-signup'
    | '/dashboard/appointments'
    | '/dashboard/billing'
    | '/dashboard/chat'
    | '/dashboard/doctors'
    | '/dashboard/home'
    | '/dashboard/my-calendar'
    | '/dashboard/my-prescriptions'
    | '/dashboard/pharmacy'
    | '/dashboard/profile'
    | '/dashboard/admin/billing'
    | '/dashboard/admin/inventory'
    | '/dashboard/admin/patients'
    | '/dashboard/admin/pharmacy'
    | '/dashboard/admin/prescriptions'
    | '/dashboard/cart/new-order'
    | '/dashboard/doctor/calendar'
    | '/dashboard/doctor/chat'
    | '/dashboard/doctor/patients'
    | '/dashboard/doctor/pharmacy'
    | '/dashboard/doctor/prescriptions'
    | '/dashboard/doctor/profile'
    | '/dashboard/orders/$order'
    | '/dashboard/admin/'
    | '/dashboard/cart/'
    | '/dashboard/doctor/'
    | '/dashboard/orders/'
    | '/dashboard/admin/doctor/new'
    | '/dashboard/admin/orders/$order'
    | '/dashboard/admin/doctor/'
    | '/dashboard/admin/orders/'
    | '/dashboard/doctor/appointments/'
    | '/dashboard/doctor/diagnoses/'
    | '/dashboard/doctor/appointments/$appointment/add-diagnosis'
    | '/dashboard/doctor/diagnoses/new-prescription/$dgs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  OurDoctorsRoute: typeof OurDoctorsRoute
  authAuthSigninRoute: typeof authAuthSigninRoute
  authAuthSignupRoute: typeof authAuthSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/our-doctors': {
      id: '/our-doctors'
      path: '/our-doctors'
      fullPath: '/our-doctors'
      preLoaderRoute: typeof OurDoctorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/pharmacy': {
      id: '/dashboard/pharmacy'
      path: '/pharmacy'
      fullPath: '/dashboard/pharmacy'
      preLoaderRoute: typeof DashboardPharmacyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/my-prescriptions': {
      id: '/dashboard/my-prescriptions'
      path: '/my-prescriptions'
      fullPath: '/dashboard/my-prescriptions'
      preLoaderRoute: typeof DashboardMyPrescriptionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/my-calendar': {
      id: '/dashboard/my-calendar'
      path: '/my-calendar'
      fullPath: '/dashboard/my-calendar'
      preLoaderRoute: typeof DashboardMyCalendarRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/home': {
      id: '/dashboard/home'
      path: '/home'
      fullPath: '/dashboard/home'
      preLoaderRoute: typeof DashboardHomeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/doctors': {
      id: '/dashboard/doctors'
      path: '/doctors'
      fullPath: '/dashboard/doctors'
      preLoaderRoute: typeof DashboardDoctorsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/chat': {
      id: '/dashboard/chat'
      path: '/chat'
      fullPath: '/dashboard/chat'
      preLoaderRoute: typeof DashboardChatRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/billing': {
      id: '/dashboard/billing'
      path: '/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof DashboardBillingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/appointments': {
      id: '/dashboard/appointments'
      path: '/appointments'
      fullPath: '/dashboard/appointments'
      preLoaderRoute: typeof DashboardAppointmentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/(auth)/auth-signup': {
      id: '/(auth)/auth-signup'
      path: '/auth-signup'
      fullPath: '/auth-signup'
      preLoaderRoute: typeof authAuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/auth-signin': {
      id: '/(auth)/auth-signin'
      path: '/auth-signin'
      fullPath: '/auth-signin'
      preLoaderRoute: typeof authAuthSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/orders/': {
      id: '/dashboard/orders/'
      path: '/orders'
      fullPath: '/dashboard/orders'
      preLoaderRoute: typeof DashboardOrdersIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/doctor/': {
      id: '/dashboard/doctor/'
      path: '/doctor'
      fullPath: '/dashboard/doctor'
      preLoaderRoute: typeof DashboardDoctorIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/cart/': {
      id: '/dashboard/cart/'
      path: '/cart'
      fullPath: '/dashboard/cart'
      preLoaderRoute: typeof DashboardCartIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/': {
      id: '/dashboard/admin/'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/orders/$order': {
      id: '/dashboard/orders/$order'
      path: '/orders/$order'
      fullPath: '/dashboard/orders/$order'
      preLoaderRoute: typeof DashboardOrdersOrderRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/doctor/profile': {
      id: '/dashboard/doctor/profile'
      path: '/doctor/profile'
      fullPath: '/dashboard/doctor/profile'
      preLoaderRoute: typeof DashboardDoctorProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/doctor/prescriptions': {
      id: '/dashboard/doctor/prescriptions'
      path: '/doctor/prescriptions'
      fullPath: '/dashboard/doctor/prescriptions'
      preLoaderRoute: typeof DashboardDoctorPrescriptionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/doctor/pharmacy': {
      id: '/dashboard/doctor/pharmacy'
      path: '/doctor/pharmacy'
      fullPath: '/dashboard/doctor/pharmacy'
      preLoaderRoute: typeof DashboardDoctorPharmacyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/doctor/patients': {
      id: '/dashboard/doctor/patients'
      path: '/doctor/patients'
      fullPath: '/dashboard/doctor/patients'
      preLoaderRoute: typeof DashboardDoctorPatientsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/doctor/chat': {
      id: '/dashboard/doctor/chat'
      path: '/doctor/chat'
      fullPath: '/dashboard/doctor/chat'
      preLoaderRoute: typeof DashboardDoctorChatRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/doctor/calendar': {
      id: '/dashboard/doctor/calendar'
      path: '/doctor/calendar'
      fullPath: '/dashboard/doctor/calendar'
      preLoaderRoute: typeof DashboardDoctorCalendarRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/cart/new-order': {
      id: '/dashboard/cart/new-order'
      path: '/cart/new-order'
      fullPath: '/dashboard/cart/new-order'
      preLoaderRoute: typeof DashboardCartNewOrderRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/prescriptions': {
      id: '/dashboard/admin/prescriptions'
      path: '/admin/prescriptions'
      fullPath: '/dashboard/admin/prescriptions'
      preLoaderRoute: typeof DashboardAdminPrescriptionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/pharmacy': {
      id: '/dashboard/admin/pharmacy'
      path: '/admin/pharmacy'
      fullPath: '/dashboard/admin/pharmacy'
      preLoaderRoute: typeof DashboardAdminPharmacyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/patients': {
      id: '/dashboard/admin/patients'
      path: '/admin/patients'
      fullPath: '/dashboard/admin/patients'
      preLoaderRoute: typeof DashboardAdminPatientsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/inventory': {
      id: '/dashboard/admin/inventory'
      path: '/admin/inventory'
      fullPath: '/dashboard/admin/inventory'
      preLoaderRoute: typeof DashboardAdminInventoryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/billing': {
      id: '/dashboard/admin/billing'
      path: '/admin/billing'
      fullPath: '/dashboard/admin/billing'
      preLoaderRoute: typeof DashboardAdminBillingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/doctor/diagnoses/': {
      id: '/dashboard/doctor/diagnoses/'
      path: '/doctor/diagnoses'
      fullPath: '/dashboard/doctor/diagnoses'
      preLoaderRoute: typeof DashboardDoctorDiagnosesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/doctor/appointments/': {
      id: '/dashboard/doctor/appointments/'
      path: '/doctor/appointments'
      fullPath: '/dashboard/doctor/appointments'
      preLoaderRoute: typeof DashboardDoctorAppointmentsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/orders/': {
      id: '/dashboard/admin/orders/'
      path: '/admin/orders'
      fullPath: '/dashboard/admin/orders'
      preLoaderRoute: typeof DashboardAdminOrdersIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/doctor/': {
      id: '/dashboard/admin/doctor/'
      path: '/admin/doctor'
      fullPath: '/dashboard/admin/doctor'
      preLoaderRoute: typeof DashboardAdminDoctorIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/orders/$order': {
      id: '/dashboard/admin/orders/$order'
      path: '/admin/orders/$order'
      fullPath: '/dashboard/admin/orders/$order'
      preLoaderRoute: typeof DashboardAdminOrdersOrderRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/doctor/new': {
      id: '/dashboard/admin/doctor/new'
      path: '/admin/doctor/new'
      fullPath: '/dashboard/admin/doctor/new'
      preLoaderRoute: typeof DashboardAdminDoctorNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/doctor/diagnoses/new-prescription/$dgs': {
      id: '/dashboard/doctor/diagnoses/new-prescription/$dgs'
      path: '/doctor/diagnoses/new-prescription/$dgs'
      fullPath: '/dashboard/doctor/diagnoses/new-prescription/$dgs'
      preLoaderRoute: typeof DashboardDoctorDiagnosesNewPrescriptionDgsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/doctor/appointments/$appointment/add-diagnosis': {
      id: '/dashboard/doctor/appointments/$appointment/add-diagnosis'
      path: '/doctor/appointments/$appointment/add-diagnosis'
      fullPath: '/dashboard/doctor/appointments/$appointment/add-diagnosis'
      preLoaderRoute: typeof DashboardDoctorAppointmentsAppointmentAddDiagnosisRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAppointmentsRoute: typeof DashboardAppointmentsRoute
  DashboardBillingRoute: typeof DashboardBillingRoute
  DashboardChatRoute: typeof DashboardChatRoute
  DashboardDoctorsRoute: typeof DashboardDoctorsRoute
  DashboardHomeRoute: typeof DashboardHomeRoute
  DashboardMyCalendarRoute: typeof DashboardMyCalendarRoute
  DashboardMyPrescriptionsRoute: typeof DashboardMyPrescriptionsRoute
  DashboardPharmacyRoute: typeof DashboardPharmacyRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardAdminBillingRoute: typeof DashboardAdminBillingRoute
  DashboardAdminInventoryRoute: typeof DashboardAdminInventoryRoute
  DashboardAdminPatientsRoute: typeof DashboardAdminPatientsRoute
  DashboardAdminPharmacyRoute: typeof DashboardAdminPharmacyRoute
  DashboardAdminPrescriptionsRoute: typeof DashboardAdminPrescriptionsRoute
  DashboardCartNewOrderRoute: typeof DashboardCartNewOrderRoute
  DashboardDoctorCalendarRoute: typeof DashboardDoctorCalendarRoute
  DashboardDoctorChatRoute: typeof DashboardDoctorChatRoute
  DashboardDoctorPatientsRoute: typeof DashboardDoctorPatientsRoute
  DashboardDoctorPharmacyRoute: typeof DashboardDoctorPharmacyRoute
  DashboardDoctorPrescriptionsRoute: typeof DashboardDoctorPrescriptionsRoute
  DashboardDoctorProfileRoute: typeof DashboardDoctorProfileRoute
  DashboardOrdersOrderRoute: typeof DashboardOrdersOrderRoute
  DashboardAdminIndexRoute: typeof DashboardAdminIndexRoute
  DashboardCartIndexRoute: typeof DashboardCartIndexRoute
  DashboardDoctorIndexRoute: typeof DashboardDoctorIndexRoute
  DashboardOrdersIndexRoute: typeof DashboardOrdersIndexRoute
  DashboardAdminDoctorNewRoute: typeof DashboardAdminDoctorNewRoute
  DashboardAdminOrdersOrderRoute: typeof DashboardAdminOrdersOrderRoute
  DashboardAdminDoctorIndexRoute: typeof DashboardAdminDoctorIndexRoute
  DashboardAdminOrdersIndexRoute: typeof DashboardAdminOrdersIndexRoute
  DashboardDoctorAppointmentsIndexRoute: typeof DashboardDoctorAppointmentsIndexRoute
  DashboardDoctorDiagnosesIndexRoute: typeof DashboardDoctorDiagnosesIndexRoute
  DashboardDoctorAppointmentsAppointmentAddDiagnosisRoute: typeof DashboardDoctorAppointmentsAppointmentAddDiagnosisRoute
  DashboardDoctorDiagnosesNewPrescriptionDgsRoute: typeof DashboardDoctorDiagnosesNewPrescriptionDgsRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAppointmentsRoute: DashboardAppointmentsRoute,
  DashboardBillingRoute: DashboardBillingRoute,
  DashboardChatRoute: DashboardChatRoute,
  DashboardDoctorsRoute: DashboardDoctorsRoute,
  DashboardHomeRoute: DashboardHomeRoute,
  DashboardMyCalendarRoute: DashboardMyCalendarRoute,
  DashboardMyPrescriptionsRoute: DashboardMyPrescriptionsRoute,
  DashboardPharmacyRoute: DashboardPharmacyRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardAdminBillingRoute: DashboardAdminBillingRoute,
  DashboardAdminInventoryRoute: DashboardAdminInventoryRoute,
  DashboardAdminPatientsRoute: DashboardAdminPatientsRoute,
  DashboardAdminPharmacyRoute: DashboardAdminPharmacyRoute,
  DashboardAdminPrescriptionsRoute: DashboardAdminPrescriptionsRoute,
  DashboardCartNewOrderRoute: DashboardCartNewOrderRoute,
  DashboardDoctorCalendarRoute: DashboardDoctorCalendarRoute,
  DashboardDoctorChatRoute: DashboardDoctorChatRoute,
  DashboardDoctorPatientsRoute: DashboardDoctorPatientsRoute,
  DashboardDoctorPharmacyRoute: DashboardDoctorPharmacyRoute,
  DashboardDoctorPrescriptionsRoute: DashboardDoctorPrescriptionsRoute,
  DashboardDoctorProfileRoute: DashboardDoctorProfileRoute,
  DashboardOrdersOrderRoute: DashboardOrdersOrderRoute,
  DashboardAdminIndexRoute: DashboardAdminIndexRoute,
  DashboardCartIndexRoute: DashboardCartIndexRoute,
  DashboardDoctorIndexRoute: DashboardDoctorIndexRoute,
  DashboardOrdersIndexRoute: DashboardOrdersIndexRoute,
  DashboardAdminDoctorNewRoute: DashboardAdminDoctorNewRoute,
  DashboardAdminOrdersOrderRoute: DashboardAdminOrdersOrderRoute,
  DashboardAdminDoctorIndexRoute: DashboardAdminDoctorIndexRoute,
  DashboardAdminOrdersIndexRoute: DashboardAdminOrdersIndexRoute,
  DashboardDoctorAppointmentsIndexRoute: DashboardDoctorAppointmentsIndexRoute,
  DashboardDoctorDiagnosesIndexRoute: DashboardDoctorDiagnosesIndexRoute,
  DashboardDoctorAppointmentsAppointmentAddDiagnosisRoute:
    DashboardDoctorAppointmentsAppointmentAddDiagnosisRoute,
  DashboardDoctorDiagnosesNewPrescriptionDgsRoute:
    DashboardDoctorDiagnosesNewPrescriptionDgsRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  OurDoctorsRoute: OurDoctorsRoute,
  authAuthSigninRoute: authAuthSigninRoute,
  authAuthSignupRoute: authAuthSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
